#!/bin/bash
# This script starts the cross-view, cross-camera and standard proportion tests for the 60 classes lstm tests.

python lstm.py -s 27 -ls 200,200 -dop 'pickles/60_classes/3d_points_global_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_3D_global' -sn
python lstm.py -s 27 -ls 200,200 -dop 'pickles/60_classes/3d_points_local_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_3D_local' -sn
python lstm.py -s 84 -ls 200,200 -dop 'pickles/60_classes/hoj_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_hoj' -sn
python lstm.py -s 88 -ls 200,200 -dop 'pickles/60_classes/hoj_parts_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_hoj_parts' -sn
python lstm.py -s 168 -ls 200,200 -dop 'pickles/60_classes/hoj_cylinder_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_hoj_cylinder' -sn
python lstm.py -s 172 -ls 200,200 -dop 'pickles/60_classes/hoj_cylinder_parts_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_hoj_cylinder_parts' -sn
python lstm.py -s 168 -ls 200,200 -dop 'pickles/60_classes/hoj_sphere_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_hoj_sphere' -sn
python lstm.py -s 172 -ls 200,200 -dop 'pickles/60_classes/hoj_sphere_parts_full.bin_data' -e 50 -tl 'P001,P002,P004,P005,P008,P009,P013,P014,P015,P016,P017,P018,P019,P025,P027,P028,P031,P034,P035,P038' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cs_hoj_sphere_parts' -sn

python lstm.py -s 27 -ls 200,200 -dop 'pickles/60_classes/3d_points_global_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_3D_global' -sn
python lstm.py -s 27 -ls 200,200 -dop 'pickles/60_classes/3d_points_local_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_3D_local' -sn
python lstm.py -s 84 -ls 200,200 -dop 'pickles/60_classes/hoj_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_hoj' -sn
python lstm.py -s 88 -ls 200,200 -dop 'pickles/60_classes/hoj_parts_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_hoj_parts' -sn
python lstm.py -s 168 -ls 200,200 -dop 'pickles/60_classes/hoj_cylinder_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_hoj_cylinder' -sn
python lstm.py -s 172 -ls 200,200 -dop 'pickles/60_classes/hoj_cylinder_parts_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_hoj_cylinder_parts' -sn
python lstm.py -s 168 -ls 200,200 -dop 'pickles/60_classes/hoj_sphere_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_hoj_sphere' -sn
python lstm.py -s 172 -ls 200,200 -dop 'pickles/60_classes/hoj_sphere_parts_full.bin_data' -e 50 -tl 'C002,C003' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/cc_hoj_sphere_parts' -sn

python lstm.py -s 27 -ls 200,200 -dop 'pickles/60_classes/3d_points_global_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_3D_global' -sn
python lstm.py -s 27 -ls 200,200 -dop 'pickles/60_classes/3d_points_local_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_3D_local' -sn
python lstm.py -s 84 -ls 200,200 -dop 'pickles/60_classes/hoj_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_hoj' -sn
python lstm.py -s 88 -ls 200,200 -dop 'pickles/60_classes/hoj_parts_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_hoj_parts' -sn
python lstm.py -s 168 -ls 200,200 -dop 'pickles/60_classes/hoj_cylinder_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_hoj_cylinder' -sn
python lstm.py -s 172 -ls 200,200 -dop 'pickles/60_classes/hoj_cylinder_parts_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_hoj_cylinder_parts' -sn
python lstm.py -s 168 -ls 200,200 -dop 'pickles/60_classes/hoj_sphere_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_hoj_sphere' -sn
python lstm.py -s 172 -ls 200,200 -dop 'pickles/60_classes/hoj_sphere_parts_full.bin_data' -e 50 -pp '80/20' -b 32 -a 'relu' -ra 'hard_sigmoid' -oN '60_classes/pp_hoj_sphere_parts' -sn